# Generated by Django 3.0 on 2020-11-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Brief description of first blog post'),
            preserve_default=False,
        ),
    ]
