# Generated by Django 3.0 on 2020-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201114_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FAMILY', 'Family'), ('GARDEN', 'Garden'), ('COOKING', 'Cooking')], default='', max_length=25),
        ),
    ]
