# Generated by Django 3.0 on 2020-11-17 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/blogs/images/'),
            preserve_default=False,
        ),
    ]
